# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
---
include:
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: prototype_mk1-reset

  - board: nice_nano_v2
    shield: prototype_mk1_dongle oled_adapter_pro_micro_128x64
    artifact-name: prototype_mk1-dongle
    cmake-args: -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=n

  - board: nice_nano_v2
    shield: prototype_mk1_left nice_view_adapter nice_oled_prototype_mk1
    artifact-name: prototype_mk1-left-perif
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: nice_nano_v2
    shield: prototype_mk1_left nice_view_adapter nice_oled_prototype_mk1
    artifact-name: prototype_mk1-left-central

  - board: nice_nano_v2
    shield: prototype_mk1_right nice_view_adapter nice_oled_prototype_mk1
    artifact-name: prototype_mk1-right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
